### ISSUE TITLE
Cannot upload source maps

### ISSUE THREAD

**Issue by h2non** [MindscapeHQ/gulp-raygun-sourcemaps#2]
I'm getting as response by the API:

``` json
{"Status":"Failure","Message":"Authorization Failed"}' } {"Status":"Failure","Message":"Authorization Failed"}
```

The App ID and key are properly defined and sent by path and `Authorization` header.

**Comment by dwnz** [comment]
Hey,

Are you able to send an email to support@raygun.io with your grunt config? I'm more than happy to have a look into this! Just don't want to place your API keys in a public place.

Cheers,
Daniel

**Comment by h2non** [comment]
Done!

**Comment by h2non** [comment]
Fixed. Closing.
